/*
 *
 * Copyright (c) 2006-2011 Sam Collett (http://www.texotela.co.uk)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 * 
 * Version 1.3.1
 * Demo: http://www.texotela.co.uk/code/jquery/numeric/
 *
 */
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('(w($){$.n.h=w(v,y){a(E v===\'1d\'){v={g:v}}v=v||{};a(E v.t=="Y"){v.t=m}f g=(v.g===B)?"":v.g||".";f t=(v.t===m)?m:B;y=(E(y)=="w"?y:w(){});q l.u("h.g",g).u("h.t",t).u("h.y",y).I($.n.h.I).N($.n.h.N).J($.n.h.J)};$.n.h.I=w(e){f g=$.u(l,"h.g");f t=$.u(l,"h.t");f b=e.K?e.K:e.M?e.M:0;a(b==13&&l.1h.1k()=="1f"){q m}C a(b==13){q B}f x=B;a((e.A&&b==1l)||(e.A&&b==1p)){q m}a((e.A&&b==1t)||(e.A&&b==1w)){q m}a((e.A&&b==1y)||(e.A&&b==1A)){q m}a((e.A&&b==1B)||(e.A&&b==1D)){q m}a((e.A&&b==1F)||(e.A&&b==1H)||(e.1i&&b==11)){q m}a(b==P||b==8||b==14||b==16){q m}a(b<1r||b>1n){f s=$(l).c();a(s.G("-")!==0&&t&&b==11&&(s.z===0||1v($.n.R(l),10)===0)){q m}a(g&&b==g.Z(0)&&s.G(g)!=-1){x=B}a(b!=8&&b!=9&&b!=13&&b!=1e&&b!=1s&&b!=14&&b!=16&&b!=P){x=B}C{a(E e.K!="Y"){a(e.M==e.F&&e.F!==0){x=m;a(e.F==P||e.F==8){x=B}}C a(e.M!==0&&e.K===0&&e.F===0){x=m}}}a(g&&b==g.Z(0)){a(s.G(g)==-1){x=m}C{x=B}}}C{x=m}q x};$.n.h.N=w(e){f c=$(l).s;a(c&&c.z>0){f 1b=$.n.R(l);f g=$.u(l,"h.g");f t=$.u(l,"h.t");a(g!==""&&g!==L){f O=c.G(g);a(O===0){l.s="0"+c}a(O==1&&c.W(0)=="-"){l.s="-0"+c.D(1)}c=l.s}f T=[0,1,2,3,4,5,6,7,8,9,\'-\',g];f z=c.z;Q(f i=z-1;i>=0;i--){f H=c.W(i);a(i!==0&&H=="-"){c=c.D(0,i)+c.D(i+1)}C a(i===0&&!t&&H=="-"){c=c.D(1)}f V=B;Q(f j=0;j<T.z;j++){a(H==T[j]){V=m;1o}}a(!V||H==" "){c=c.D(0,i)+c.D(i+1)}}f X=c.G(g);a(X>0){Q(f k=z-1;k>X;k--){f 15=c.W(k);a(15==g){c=c.D(0,k)+c.D(k+1)}}}l.s=c;$.n.19(l,1b)}};$.n.h.J=w(){f g=$.u(l,"h.g");f y=$.u(l,"h.y");f c=l.s;a(c!==""){f 1c=1g 1E("^\\\\d+$|^\\\\d*"+g+"\\\\d+$");a(!1c.1u(c)){y.1O(l)}}};$.n.1K=w(){q l.u("h.g",L).u("h.t",L).u("h.y",L).12("I",$.n.h.I).12("J",$.n.h.J)};$.n.R=w(o){a(o.U){f r=1m.1z.1I().1M();r.17(\'S\',o.s.z);a(r.1a===\'\'){q o.s.z}q o.s.1j(r.1a)}C{q o.1G}};$.n.19=w(o,p){a(E p=="1x"){p=[p,p]}a(p&&p.1q==1J&&p.z==2){a(o.U){f r=o.U();r.1N(m);r.1Q(\'S\',p[0]);r.17(\'S\',p[1]);r.1C()}C a(o.18){o.1L();o.18(p[0],p[1])}}}})(1P);',62,115,'||||||||||if|key|val|||var|decimal|numeric||||this|true|fn|||return||value|negative|data|config|function|allow|callback|length|ctrlKey|false|else|substring|typeof|which|indexOf|ch|keypress|blur|charCode|null|keyCode|keyup|dot|46|for|getSelectionStart|character|validChars|createTextRange|validChar|charAt|firstDecimal|undefined|charCodeAt||45|unbind||37|chch|39|moveEnd|setSelectionRange|setSelection|text|carat|re|boolean|35|input|new|nodeName|shiftKey|lastIndexOf|toLowerCase|97|document|57|break|65|constructor|48|36|120|exec|parseInt|88|number|99|selection|67|122|select|90|RegExp|118|selectionStart|86|createRange|Array|removeNumeric|focus|duplicate|collapse|apply|jQuery|moveStart'.split('|'),0,{}))